### ISSUE TITLE
Fields in zendesk pipelines

### ISSUE THREAD

**Issue by Yuchangz** [dlt-hub/pipelines#139]
**Pipeline name**
zendesk
**Describe the bug**
in Zendesk souce like  tickets,
1. there are values in the column that has prefix like  ` __dc.cc_--_cm_-_ `. This kind of prefix needs to remove. e.g. there is a value in column `contact_reason` : `"__dc.cc_--_cm_-_i_am_unable_to_check_in__"`, it should look like `Check in Management::I am unable to check in`. 

**To Reproduce**

**Expected behavior**
I would like to remove the prefix
**Stack traces and other evidence**
<img width="502" alt="Screenshot 2023-05-11 at 15 17 05" src="https://github.com/dlt-hub/pipelines/assets/97105650/6ba9cc86-5cf5-4289-a300-593d59e579a9">
**Running environment**
- Cloud Composer
- dlt Version - 0.2.6a1

**Comment by steinitzu** [comment]
Hey @Yuchangz   
I'm looking into this now. Is this a custom dropdown field that you're dealing with?  
The zendesk API returns normalized values for these fields instead of the display text. E.g. the "tag" value:  
![custom-field](https://github.com/dlt-hub/pipelines/assets/1033963/f8907a71-9f00-4d3e-91db-5e985169d732)

Just to confirm this is the same issue that's affecting you. I'll add a step to map the values to our custom field logic.

**Comment by rudolfix** [comment]
@steinitzu yeah it seems that we need to rename those tags. Yuchang is offline for some time. Let's move forward with your fix. thanks!

**Comment by rudolfix** [comment]
@Yuchangz this issue is fixed, the layout of state has changed so we need to load the data from scratch to a new dataset
